/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class AppTest {
    // @Test public void appHasAGreeting() {
    //     Main classUnderTest = new Main();
        // assertNotNull("app should have a greeting", classUnderTest.());
    // }
}
